spring:
  application:
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222/api/v1/products
      payment-url: http://localhost:8222/api/v1/payments
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: agam
    password: agam
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.agam.ecommerce.kafka.OrderConfirmation
server:
  port: 8070
